# Telegram Bot Configuration
telegram:
  token: "your_telegram_bot_token"
  allowed_usernames:
    - "your_telegram_username"
  debug: false

# Deriv API Configuration
deriv:
  app_id: "your_deriv_app_id"
  api_token: "your_deriv_api_token"
  endpoint: "wss://ws.binaryws.com/websockets/v3"
  symbols:
    - "R_10"
    - "R_25"
    - "R_50"
    - "R_75"
    - "R_100"

# LLM Configuration
llm:
  api_key: "your_anthropic_api_key"
  model: "claude-2" # Optional, defaults to claude-2
